name: Doom Wasm PWA Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: multi_select_doom

      - name: Install Emscripten and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake python3-pip libssl-dev
          sudo pip3 install conan
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: Build with Emscripten
        run: |
          sudo apt install automake libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev -y
          source ./emsdk_env.sh
          ./scripts/build.sh

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src
